version: "3.9"

services:
  symfony:
    build: .
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony_net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
    networks:
      - symfony_net

networks:
  symfony_net:
